import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeModal } from './SafeModal';
import { api } from '../services/api';
import { useLiveRefresh } from '../services/live';
import type { InAppNotification } from '../types/models';
import { ui } from '../theme/ui';
const destinations:Record<string,string>={message:'messages',agreement:'agreements',expense:'expenses',expense_payment:'expenses',event:'calendar',custody_exception:'permanence',document:'documents',child:'children'};
export function NotificationPreview({visible,onClose,onNavigate}:{visible:boolean;onClose:()=>void;onNavigate:(screen:string)=>void}){
 const [items,setItems]=useState<InAppNotification[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!visible)return;try{setError('');setItems((await api.notifications.list()).slice(0,6));}catch(e){setError(e instanceof Error?e.message:'Impossibile caricare le notifiche.');}finally{setLoading(false);}},[visible]);
 useEffect(()=>{if(visible){setLoading(true);void load();}},[visible,load]);useLiveRefresh(load);
 async function open(item:InAppNotification){try{if(!item.readAt)await api.notifications.markRead(item.id);onClose();onNavigate(destinations[item.entityType??'']??'notifications');}catch(e){setError(e instanceof Error?e.message:'Operazione non riuscita.');}}
 return <SafeModal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.overlay}><Pressable style={StyleSheet.absoluteFill} accessibilityLabel="Chiudi anteprima notifiche" onPress={onClose}/><View style={s.panel}><View style={s.header}><Text style={s.title}>Ultime notifiche</Text><Pressable accessibilityLabel="Chiudi" onPress={onClose} style={{padding:10}}><Text style={s.link}>Chiudi</Text></Pressable></View>{loading?<ActivityIndicator style={{padding:24}}/>:<ScrollView style={{maxHeight:380}} contentContainerStyle={{padding:12,gap:8}}>{!!error&&<Pressable onPress={()=>void load()}><Text style={{color:ui.colors.danger}}>{error} · Riprova</Text></Pressable>}{!error&&!items.length&&<Text style={{padding:16,color:ui.colors.muted}}>Nessuna notifica.</Text>}{items.map(item=><Pressable accessibilityRole="button" key={item.id} onPress={()=>void open(item)} style={[s.item,!item.readAt&&{backgroundColor:ui.colors.primarySoft}]}><View style={{flexDirection:'row',gap:8,alignItems:'center'}}>{!item.readAt&&<View style={s.dot}/>}<Text style={s.itemTitle}>{item.title}</Text></View><Text numberOfLines={3} style={s.body}>{item.body}</Text><Text style={s.time}>{new Date(item.createdAt).toLocaleString('it-IT')}</Text></Pressable>)}</ScrollView>}<Pressable style={s.footer} onPress={()=>{onClose();onNavigate('notifications');}}><Text style={s.link}>Vedi tutte</Text></Pressable></View></View></SafeModal>;
}
const s=StyleSheet.create({overlay:{flex:1,alignItems:'flex-end',padding:12,backgroundColor:'rgba(12,43,99,.2)'},panel:{width:'100%',maxWidth:420,maxHeight:'90%',backgroundColor:'white',borderRadius:20,overflow:'hidden'},header:{paddingLeft:16,paddingRight:6,paddingVertical:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:19,fontWeight:'800',color:ui.colors.primaryDark},item:{padding:12,borderRadius:12,gap:5},itemTitle:{fontWeight:'800',color:ui.colors.primaryDark,flex:1},body:{color:ui.colors.text,lineHeight:20},time:{fontSize:11,color:ui.colors.muted},dot:{width:8,height:8,borderRadius:4,backgroundColor:ui.colors.primary},footer:{padding:16,alignItems:'center',borderTopWidth:1,borderColor:ui.colors.border},link:{color:ui.colors.primary,fontWeight:'800'}});
