import * as ImagePicker from 'expo-image-picker';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import type { Expense, ExpenseCategory, FamilyBalance } from '../types/models';

const categories:ExpenseCategory[]=['Scuola','Salute','Sport','Svago'];
type Receipt={uri:string;name:string;type:string;file?:Blob};
const euro=(v:string)=>`${Number(v).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2})} €`;
const statusLabel=(s:Expense['status'])=>s==='approved'?'Approvata':s==='declined'?'Contestata':'Da approvare';

export function ExpensesScreen():React.JSX.Element{
  const {user}=useAuth(); const [items,setItems]=useState<Expense[]>([]); const [balance,setBalance]=useState<FamilyBalance|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [form,setForm]=useState(false); const [busy,setBusy]=useState<string|null>(null); const [receipt,setReceipt]=useState<Expense|null>(null);
  const load=useCallback(async()=>{try{const [e,b]=await Promise.all([api.expenses.list(),api.expenses.balance()]);setItems(e);setBalance(b);}catch(err){Alert.alert('Spese',err instanceof Error?err.message:'Errore di caricamento');}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function review(e:Expense,action:'approve'|'decline'){try{setBusy(e.id);action==='approve'?await api.expenses.approve(e.id):await api.expenses.decline(e.id);await load();}catch(err){Alert.alert('Spesa',err instanceof Error?err.message:'Operazione non riuscita');}finally{setBusy(null);}}
  if(loading)return <View style={s.center}><ActivityIndicator size="large"/><Text>Caricamento spese…</Text></View>;
  const message=!balance||balance.direction==='settled'?'Siete in pari':balance.direction==='receive'?`Devi ricevere ${euro(balance.settlementAmount)}`:`Devi dare ${euro(balance.settlementAmount)}`;
  return <View style={s.screen}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>}>
    <View style={s.head}><View><Text style={s.title}>Spese condivise</Text><Text style={s.muted}>Divisione trasparente al 50%.</Text></View><Pressable style={s.add} onPress={()=>setForm(true)}><Text style={s.addT}>+ Aggiungi</Text></Pressable></View>
    <View style={s.balance}><Text style={s.balanceLabel}>BILANCIO ATTUALE</Text><Text style={s.balanceValue}>{message}</Text>{balance?<Text style={s.balanceMeta}>Padre {euro(balance.fatherPaid)} · Madre {euro(balance.motherPaid)} · quota {euro(balance.perParentShare)}</Text>:null}</View>
    <Text style={s.section}>Movimenti</Text>
    {items.length===0?<View style={s.card}><Text style={s.bold}>Nessuna spesa</Text><Text style={s.muted}>Aggiungi la prima spesa condivisa.</Text></View>:items.map(e=><View key={e.id} style={s.card}>
      <View style={s.head}><View style={{flex:1}}><Text style={s.bold}>{e.title}</Text><Text style={s.meta}>{e.category} · {new Date(`${e.expenseDate}T12:00:00`).toLocaleDateString('it-IT')} · pagata da {e.paidByName??(e.paidByRole==='father'?'Padre':'Madre')}</Text></View><Text style={s.amount}>{euro(e.amount)}</Text></View>
      <Text style={[s.pill,e.status==='approved'?s.ok:e.status==='declined'?s.no:s.pending]}>{statusLabel(e.status)}</Text>{e.notes?<Text style={s.muted}>{e.notes}</Text>:null}
      <View style={s.actions}>{e.receiptUrl?<Pressable style={s.secondary} onPress={()=>setReceipt(e)}><Text style={s.secondaryT}>Ricevuta</Text></Pressable>:null}{e.canReview?<><Pressable disabled={busy===e.id} style={s.decline} onPress={()=>void review(e,'decline')}><Text style={s.declineT}>Contesta</Text></Pressable><Pressable disabled={busy===e.id} style={s.approve} onPress={()=>void review(e,'approve')}><Text style={s.approveT}>Approva spesa</Text></Pressable></>:null}</View>
    </View>)}
  </ScrollView><ExpenseModal visible={form} onClose={()=>setForm(false)} onDone={e=>{setItems(v=>[e,...v]);setForm(false);void load();}}/>
  <Modal visible={receipt!==null} transparent animationType="fade" onRequestClose={()=>setReceipt(null)}><View style={s.backdrop}><View style={s.preview}><View style={s.head}><Text style={s.bold}>Ricevuta</Text><Pressable onPress={()=>setReceipt(null)}><Text style={s.close}>×</Text></Pressable></View>{receipt?.receiptUrl?<Image source={api.expenses.receiptSource(receipt.receiptUrl)} resizeMode="contain" style={s.image}/>:null}</View></View></Modal></View>;
}

function ExpenseModal({visible,onClose,onDone}:{visible:boolean;onClose:()=>void;onDone:(e:Expense)=>void}):React.JSX.Element{
  const [title,setTitle]=useState('');const [amount,setAmount]=useState('');const [category,setCategory]=useState<ExpenseCategory>('Scuola');const [notes,setNotes]=useState('');const [receipt,setReceipt]=useState<Receipt|null>(null);const [busy,setBusy]=useState(false);
  async function fromLibrary(){const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted){Alert.alert('Permesso richiesto','Consenti l’accesso alle foto.');return;}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8});if(r.canceled)return;const a=r.assets[0];if(a)setReceipt({uri:a.uri,name:a.fileName??`ricevuta-${Date.now()}.jpg`,type:a.mimeType??'image/jpeg',file:a.file});}
  async function fromCamera(){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){Alert.alert('Permesso richiesto','Consenti l’uso della fotocamera.');return;}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.8});if(r.canceled)return;const a=r.assets[0];if(a)setReceipt({uri:a.uri,name:a.fileName??`ricevuta-${Date.now()}.jpg`,type:a.mimeType??'image/jpeg',file:a.file});}
  async function save(){const normalized=amount.trim().replace(',','.');if(!title.trim()||!/^\d{1,10}(?:\.\d{1,2})?$/.test(normalized)||Number(normalized)<=0){Alert.alert('Spesa','Inserisci titolo e importo valido.');return;}try{setBusy(true);const e=await api.expenses.create({title:title.trim(),amount:normalized,category,notes:notes.trim()||undefined,receipt:receipt??undefined});onDone(e);setTitle('');setAmount('');setNotes('');setReceipt(null);}catch(err){Alert.alert('Spesa',err instanceof Error?err.message:'Salvataggio non riuscito');}finally{setBusy(false);}}
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><ScrollView contentContainerStyle={s.modal}><Text style={s.modalTitle}>Aggiungi spesa</Text><Text style={s.label}>Titolo</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Es. Libri scolastici"/><Text style={s.label}>Importo (€)</Text><TextInput style={s.input} value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0,00"/><Text style={s.label}>Categoria</Text><View style={s.chips}>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.chip,category===c&&s.chipOn]}><Text>{c}</Text></Pressable>)}</View><Text style={s.label}>Nota</Text><TextInput style={[s.input,{minHeight:80}]} multiline value={notes} onChangeText={setNotes}/><Text style={s.label}>Ricevuta (facoltativa)</Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>void fromCamera()}><Text style={s.secondaryT}>Scatta foto</Text></Pressable><Pressable style={s.secondary} onPress={()=>void fromLibrary()}><Text style={s.secondaryT}>Galleria</Text></Pressable></View>{receipt?<Text style={s.muted}>Allegato: {receipt.name}</Text>:null}<View style={s.actions}><Pressable style={s.secondary} onPress={onClose}><Text>Annulla</Text></Pressable><Pressable disabled={busy} style={s.approve} onPress={()=>void save()}><Text style={s.approveT}>{busy?'Salvataggio…':'Salva spesa'}</Text></Pressable></View></ScrollView></View></Modal>;
}

const s=StyleSheet.create({screen:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},content:{padding:18,gap:14,paddingBottom:36},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12},title:{fontSize:28,fontWeight:'900',color:'#0F172A'},muted:{color:'#64748B',lineHeight:20},add:{backgroundColor:'#4F46E5',padding:11,borderRadius:12},addT:{color:'#FFF',fontWeight:'900'},balance:{backgroundColor:'#312E81',borderRadius:22,padding:20,gap:6},balanceLabel:{color:'#C7D2FE',fontWeight:'900',fontSize:11,letterSpacing:1.2},balanceValue:{color:'#FFF',fontSize:28,fontWeight:'900'},balanceMeta:{color:'#E0E7FF'},section:{fontSize:20,fontWeight:'900'},card:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:17,padding:15,gap:10},bold:{fontWeight:'900',color:'#0F172A'},meta:{fontSize:12,color:'#64748B'},amount:{fontSize:18,fontWeight:'900',color:'#0F172A'},pill:{alignSelf:'flex-start',paddingHorizontal:9,paddingVertical:5,borderRadius:999,fontWeight:'800',overflow:'hidden'},ok:{backgroundColor:'#DCFCE7',color:'#166534'},no:{backgroundColor:'#FFE4E6',color:'#BE123C'},pending:{backgroundColor:'#FEF3C7',color:'#92400E'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},secondary:{flex:1,minWidth:90,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:12,borderWidth:1,borderColor:'#CBD5E1',backgroundColor:'#F8FAFC',paddingHorizontal:10},secondaryT:{fontWeight:'800',color:'#475569'},decline:{flex:1,minWidth:90,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#FFF1F2'},declineT:{color:'#BE123C',fontWeight:'900'},approve:{flex:1,minWidth:110,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#16A34A'},approveT:{color:'#FFF',fontWeight:'900'},backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(15,23,42,.5)'},modal:{backgroundColor:'#FFF',padding:20,paddingBottom:30,borderTopLeftRadius:26,borderTopRightRadius:26,gap:10},modalTitle:{fontSize:22,fontWeight:'900'},label:{fontWeight:'800',color:'#334155'},input:{minHeight:48,borderWidth:1,borderColor:'#CBD5E1',borderRadius:12,paddingHorizontal:12,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:999,backgroundColor:'#F1F5F9'},chipOn:{backgroundColor:'#C7D2FE'},preview:{backgroundColor:'#FFF',margin:18,borderRadius:20,padding:14,gap:12},close:{fontSize:28},image:{width:'100%',height:500,backgroundColor:'#F8FAFC'}});
