export const ui = {
  colors: {
    background: 'rgba(255, 249, 240, 0.96)',
    backgroundSolid: '#FFF9F0',
    card: '#FFFEFB',
    primary: '#1769E0',
    primaryDark: '#0C2B63',
    primarySoft: '#EAF4FF',
    sky: '#BFE1FF',
    skySoft: '#F1F8FF',
    orange: '#FF922E',
    orangeDark: '#E67212',
    orangeSoft: '#FFF0DD',
    cream: '#FFF8ED',
    creamStrong: '#FFE2B9',
    input: '#F4F8FD',
    border: '#D9E7F4',
    text: '#15345F',
    muted: '#6B7F9F',
    success: '#159A68',
    successSoft: '#E7F7F0',
    danger: '#D9485F',
    dangerSoft: '#FDECEF',
    warning: '#E68719',
    warningSoft: '#FFF2DF',
  },
  gradients: {
    page: ['#EAF5FF', '#FFFDF8', '#FFF1DE'] as const,
    header: ['#DCEFFF', '#FFF8ED', '#FFE7C7'] as const,
    nav: ['#FFFFFF', '#F7FBFF', '#FFF8ED'] as const,
    primary: ['#2A7BE8', '#1769E0', '#0F5AC4'] as const,
    warm: ['#FFF8ED', '#FFEBCF', '#FFD49E'] as const,
    selected: ['#EAF4FF', '#FFF3E2'] as const,
  },
  radius: {
    sm: 11,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 30,
  },
} as const;

export const cardShadow = {
  shadowColor: '#15345F',
  shadowOpacity: 0.08,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 7 },
  elevation: 3,
} as const;
